### ISSUE TITLE
关于 Disucz新版ssrf

### ISSUE THREAD

**Issue by schwanncheung** [leveryd/leveryd.github.io#1]
请教一下，您这篇文中提到的补丁在哪里下载呢？官方论坛没有找到补丁
https://leveryd.github.io/2017-11-01-Disucz%E6%96%B0%E7%89%88ssrf/

**Comment by leveryd** [comment]
https://gitee.com/ComsenzDiscuz/DiscuzX/commit/19fd20f7420397b88278ac1a0dae65fe50012506

**Comment by leveryd** [comment]
discuz代码托管在码云上。

**Comment by schwanncheung** [comment]
谢谢！
不过，码云上只有 3.X 版本的，2.X 的补丁估计没有了吧
